services:
  db:
    image: pgvector/pgvector:pg16
    container_name: laburen_db
    environment:
      POSTGRES_DB: laburen_ai_agent
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U \"$${POSTGRES_USER}\" -d \"${POSTGRES_DB:-postgres}\""]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 60s
    restart: unless-stopped
    networks: [internal]

  ollama:
    image: ollama/ollama:latest
    container_name: laburen_ollama
    volumes:
      - ollama_data:/root/.ollama
    expose:
      - "11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped
    networks: [internal]

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: https://jereprograma.com
    container_name: laburen_app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://app:app@db:5432/laburen_ai_agent
      OLLAMA_BASE_URL: http://ollama:11434
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_MODEL: ${OPENROUTER_MODEL:-anthropic/claude-3.5-haiku}
      DOCS_ROOT: ../data
      MAX_TOOL_ITERATIONS: 4
      EMBEDDING_MODEL: nomic-embed-text
      EMBEDDING_DIM: "768"
      NEXT_PUBLIC_BACKEND_URL: https://app.jereprograma.com
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    # No publicar 3000 al host; Caddy hace el proxy
    restart: unless-stopped
    networks: [internal]

  caddy:
    image: caddy:2
    container_name: laburen_caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: jereprograma.com
      EMAIL: admin@jereprograma.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped
    networks: [internal]

volumes:
  pg_data:
  ollama_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
